# Generated by Django 6.0.3 on 2026-03-12 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='deccription',
            new_name='description',
        ),
    ]
